name: Build Code FA APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ARM64 APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract versions
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          CSVERSION=$(grep '^code_server: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')

          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "CSVERSION=$CSVERSION" >> "$GITHUB_ENV"

          echo "Code FA version: $VERSION"
          echo "code-server version: $CSVERSION"

      - name: Download code-server ARM64
        run: |
          wget \
            -O "assets/code-server-${CSVERSION}-linux-arm64.tar.gz" \
            "https://github.com/coder/code-server/releases/download/v${CSVERSION}/code-server-${CSVERSION}-linux-arm64.tar.gz"

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Dependencies
        run: flutter pub get

      - name: Build ARM64 APK
        run: |
          flutter build apk \
            --debug \
            --target-platform android-arm64 \
            --dart-define=VERSION=${VERSION} \
            --dart-define=CSVERSION=${CSVERSION}

      - name: Rename APK
        run: |
          mkdir -p output
          cp build/app/outputs/flutter-apk/app-debug.apk \
            "output/CodeFA_${VERSION}_Android_arm64_debug.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CodeFA-Android-arm64
          path: output/*.apk
          if-no-files-found: error
